/** 화면에 보이는 모든 한글 문구를 한 곳에 모아둔다. 문구 수정은 이 파일만 고치면 된다. */
export const UI_TEXT = {
  common: {
    serviceName: "함께 그리는 우리 숲",
    back: "뒤로 가기",
    help: "도움말",
    loading: "잠시만 기다려 주세요",
    confirmYes: "네",
    confirmNo: "아니요",
    orientationTitle: "태블릿을 옆으로 돌려주세요",
    orientationBody: "이 화면은 눕혀서 봐야 더 예뻐요!",
  },
  login: {
    title: "팔찌에 적힌 번호를 눌러주세요",
    subtitle: "숫자 6개를 눌러 주세요",
    clear: "지우기",
    clearAll: "모두 지우기",
    submit: "시작하기",
    softError: "번호를 한 번 더 확인해 주세요.",
    checking: "확인하고 있어요...",
  },
  weeklyTheme: {
    eyebrow: "이번 주의 주제",
    footerNote: "친구들과 함께 하나의 그림을 완성해요!",
    skip: "건너뛰기",
  },
  assignment: {
    heading: (nickname: string) => `${nickname} 친구가 맡은 그림이에요!`,
    subtitle: "내가 색칠할 부분을 노란 테두리로 표시했어요",
    cta: "색칠하러 가기",
  },
  drawing: {
    themeLabel: "이번 주 주제: 나무",
    collabNote: "친구들과 함께 색칠하고 있어요",
    tools: "도구",
    colors: "색깔",
    brushSize: "굵기",
    undo: "되돌리기",
    redo: "다시하기",
    clearAll: "전체 지우기",
    preview: "미리보기",
    done: "다 그렸어요!",
    clearConfirmTitle: "그림을 모두 지울까요?",
    clearConfirmBody: "지금까지 칠한 색이 모두 사라져요.",
    autoSaving: "저장하고 있어요...",
    autoSaved: "저장 완료!",
    saveFailed: "저장하지 못했어요. 다시 시도할게요.",
    leaveConfirmTitle: "그림을 두고 나갈까요?",
    leaveConfirmBody: "지금까지 그린 그림은 저장돼요.",
  },
  brushSizes: {
    SMALL: "작게",
    MEDIUM: "보통",
    LARGE: "크게",
  },
  preview: {
    heading: "내 그림이 여기에 들어가요!",
    keepDrawing: "조금 더 그릴래요",
    sendIt: "이대로 보낼래요",
  },
  submit: {
    heading: "그림을 친구들에게 보냈어요!",
    cta: "친구들의 그림 기다리기",
  },
  waitingRoom: {
    heading: "친구들을 기다리고 있어요",
    statusWaiting: "친구 기다리는 중",
    statusDrawing: "색칠 중...",
    statusSubmitted: "색칠 완료!",
    footerCount: (count: number) => `지금 ${count}명의 친구가 함께하고 있어요`,
    footerNote: "조금만 기다리면 그림이 완성돼요!",
  },
  result: {
    heading: "친구들과 함께 나무를 완성했어요!",
    participants: "참여한 친구",
    hospital: "병원",
    date: "완성 날짜",
    theme: "이번 주 주제",
    viewLarge: "우리 그림 크게 보기",
    gallery: "작품 보관함",
    nextWeek: "다음 주제 기다리기",
  },
  gallery: {
    heading: "작품 보관함",
    empty: "아직 완성된 작품이 없어요",
    backHome: "처음으로",
  },
} as const;
